---
- name: Update apt cache.
  apt: update_cache=yes
  sudo: yes

#- name: Upgrade Raspbian.
#  apt: upgrade=yes
#  sudo: yes

- name: Setting our new hostname.
  hostname: name={{ hostname }}
  sudo: yes

- name: Generate locales to prevent annoying SSH messages.
  locale_gen: name=en_US.UTF-8 state=present
  sudo: yes

- name: Ensure base packages are installed.
  apt: "name={{ item }} state=installed"
  sudo: yes
  with_items: default_packages

- name: Uninstall wolfram-alpha engine, we don't need it
  apt: pkg={{ item }} state=absent
  sudo: yes
  with_items:
    - wolfram-engine

- name: Autoremove any unused packages.
  shell: "apt-get autoremove --assume-yes --purge"
  sudo: yes

- name: Let's Autoclean the system.
  shell: "apt-get autoclean --assume-yes"
  sudo: yes
